/**
 * TypeScript code generation from domain IR.
 *
 * The compiler validates user source code and generates only the wiring/boilerplate:
 * - Validators (pure TypeScript runtime validation)
 * - Handlers (HTTP handlers that wire aggregates to SpiteDB)
 * - Router (Bun.serve routing)
 *
 * User's source files (events.ts, state.ts, aggregate.ts) are NOT regenerated -
 * we import them directly from the domain folder.
 */

import type { DomainIR } from "../ir/index.js";
import { toSnakeCase } from "./ts-types.js";
import { generateValidators } from "./validators.js";
import { generateHandlers } from "./handlers.js";
import { generateRouter } from "./router.js";
import { generateServer } from "./server.js";

export { toSnakeCase, toCamelCase, toPascalCase, typeToTs } from "./ts-types.js";
export { generateValidators } from "./validators.js";
export { generateHandlers } from "./handlers.js";
export { generateRouter } from "./router.js";
export { generateServer } from "./server.js";

/**
 * Generated file entry.
 */
export interface GeneratedFile {
  /** File path (relative to output directory). */
  path: string;
  /** File content. */
  content: string;
}

/**
 * Generated TypeScript code.
 */
export interface GeneratedCode {
  /** Generated files. */
  files: GeneratedFile[];
}

/**
 * Generates TypeScript code from domain IR.
 *
 * Only generates wiring code (validators, handlers, router).
 * User's source files are imported directly, not regenerated.
 *
 * `domainImportPath` is the relative path from the generated handlers directory
 * to the domain source directory (e.g., "../../../../domain" for typical project structure).
 */
export function generate(domain: DomainIR, domainImportPath: string): GeneratedCode {
  const files: GeneratedFile[] = [];

  // Generate code for each aggregate
  for (const aggregate of domain.aggregates) {
    const snakeName = toSnakeCase(aggregate.name);

    // Validators - generates runtime validation for commands
    const validatorsCode = generateValidators(aggregate, domainImportPath);
    files.push({ path: `validators/${snakeName}.validator.ts`, content: validatorsCode });

    // Handlers - wires aggregates to HTTP + SpiteDB
    const handlersCode = generateHandlers(aggregate, domainImportPath);
    files.push({ path: `handlers/${snakeName}.handlers.ts`, content: handlersCode });
  }

  // Generate router
  const routerCode = generateRouter(domain);
  files.push({ path: "router.ts", content: routerCode });

  // Generate server
  const serverCode = generateServer(domain);
  files.push({ path: "server.ts", content: serverCode });

  // Generate index re-exports
  const indexCode = generateIndex(domain);
  files.push({ path: "index.ts", content: indexCode });

  return { files };
}

/**
 * Generates the index file with re-exports.
 */
function generateIndex(domain: DomainIR): string {
  const exports = domain.aggregates
    .map((agg) => {
      const snakeName = toSnakeCase(agg.name);
      return `export * from "./handlers/${snakeName}.handlers.js";
export * from "./validators/${snakeName}.validator.js";`;
    })
    .join("\n");

  return `// Generated index
// DO NOT EDIT - this file is generated by spite-compiler

${exports}
export { createRouter, routes } from "./router.js";
`;
}
