/**
 * Generates Bun.serve routing configuration.
 */

import type { DomainIR } from "../ir/index.js";
import { toSnakeCase, toPascalCase } from "./ts-types.js";

/**
 * Generates the router file.
 */
export function generateRouter(domain: DomainIR): string {
  const imports = generateImports(domain);
  const routes = generateRoutes(domain);
  const routerExport = generateRouterExport(domain);

  return `${imports}

${routes}

${routerExport}
`;
}

/**
 * Generates import statements.
 */
function generateImports(domain: DomainIR): string {
  const aggregateImports = domain.aggregates
    .map((agg) => {
      const snakeName = toSnakeCase(agg.name);
      const pascalName = toPascalCase(agg.name);
      return `import { create${pascalName}Handlers } from "./handlers/${snakeName}.handlers.js";`;
    })
    .join("\n");

  return `// Generated router
// DO NOT EDIT - this file is generated by spite-compiler

import type { SpiteDB } from "@spitestack/spitedb";

${aggregateImports}`;
}

/**
 * Generates route definitions.
 */
function generateRoutes(domain: DomainIR): string {
  const routes: string[] = [];

  for (const agg of domain.aggregates) {
    const snakeName = toSnakeCase(agg.name);
    for (const cmd of agg.commands) {
      routes.push(`  "POST /api/${snakeName}/:streamId/${cmd.name}": {
    handler: "${snakeName}.${cmd.name}",
    access: "${cmd.access}"${cmd.roles.length > 0 ? `,
    roles: ${JSON.stringify(cmd.roles)}` : ""}
  }`);
    }
  }

  return `/**
 * Route definitions.
 */
export const routes = {
${routes.join(",\n")}
} as const;`;
}

/**
 * Generates the router export.
 */
function generateRouterExport(domain: DomainIR): string {
  const handlers = domain.aggregates
    .map((agg) => {
      const snakeName = toSnakeCase(agg.name);
      const pascalName = toPascalCase(agg.name);
      return `    ${snakeName}: create${pascalName}Handlers(db)`;
    })
    .join(",\n");

  return `/**
 * Creates the application router.
 */
export function createRouter(db: SpiteDB) {
  const handlers = {
${handlers}
  };

  return {
    routes,
    handlers
  };
}`;
}
