// Generated validators for Counter
// DO NOT EDIT - this file is generated by spite-compiler

import type { CounterState, CounterEvent } from "../../domain/counter/index.js";

/**
 * Validates input for increment command.
 */
export function validateIncrement(input: unknown): { amount: number } {
  if (typeof input !== 'object' || input === null) {
    throw new Error('Input must be an object');
  }
  const obj = input as Record<string, unknown>;

  // Validate amount
  if (typeof obj.amount !== 'number') {
    throw new Error('amount must be a number');
  }
  const validated_amount = obj.amount as number;

  return {
    amount: validated_amount
  };
}

/**
 * Validates input for decrement command.
 */
export function validateDecrement(input: unknown): { amount: number } {
  if (typeof input !== 'object' || input === null) {
    throw new Error('Input must be an object');
  }
  const obj = input as Record<string, unknown>;

  // Validate amount
  if (typeof obj.amount !== 'number') {
    throw new Error('amount must be a number');
  }
  const validated_amount = obj.amount as number;

  return {
    amount: validated_amount
  };
}

/**
 * Validates input for reset command.
 */
export function validateReset(input: unknown): Record<string, never> {
  if (typeof input !== 'object' || input === null) {
    throw new Error('Input must be an object');
  }
  const obj = input as Record<string, unknown>;



  return {

  };
}
