/**
 * Projection registration types.
 *
 * The compiler generates registration objects that the runtime uses to
 * create and manage projection instances.
 */

import type { Projection, ProjectionMetadata } from './projection';
import type { StoredEvent } from '../../domain/events/stored-event';

/**
 * Registration entry for a projection.
 *
 * Generated by the compiler for each user projection class.
 * Contains metadata and a factory function to create instances.
 *
 * @typeParam TState - The serializable state type
 *
 * @example
 * ```ts
 * // Compiler-generated registration
 * export const TotalRevenueRegistration: ProjectionRegistration<number> = {
 *   metadata: {
 *     name: 'TotalRevenue',
 *     kind: 'aggregator',
 *     subscribedEvents: ['OrderCompleted', 'RefundIssued'],
 *     accessPatterns: [{ methodName: 'getTotal', indexFields: [] }],
 *   },
 *   factory: () => {
 *     const projection = new TotalRevenue();
 *     return {
 *       build: (event) => projection.build(event),
 *       getState: () => projection.total,
 *       setState: (state) => { projection.total = state; },
 *       reset: () => { projection.total = 0; },
 *     };
 *   },
 * };
 * ```
 */
export interface ProjectionRegistration<TState = unknown> {
  /** Projection metadata from compiler analysis */
  metadata: ProjectionMetadata;

  /**
   * Factory to create a new projection instance.
   *
   * Called once during startup and after recovery.
   * Returns an adapter that implements the Projection interface.
   */
  factory: () => Projection<TState>;

  /**
   * Optional: Get the underlying user class instance for query methods.
   *
   * Used by the coordinator to expose query methods to callers.
   * The factory returns the interface, but callers may need the actual class
   * to call query methods like getById(), getTotal(), etc.
   */
  getInstance?: () => unknown;
}

/**
 * Runtime options for a projection.
 *
 * Can be provided when registering to override defaults.
 */
export interface ProjectionRuntimeOptions {
  /**
   * Override checkpoint interval (milliseconds).
   * Default: 5000ms (from metadata or global default).
   */
  checkpointIntervalMs?: number;

  /**
   * Memory threshold before disk spillover (bytes).
   * Only applies to denormalized_view projections.
   * Default: 50MB.
   */
  memoryThresholdBytes?: number;

  /**
   * Enable/disable this projection.
   * Disabled projections are registered but not started.
   * Default: true.
   */
  enabled?: boolean;

  /**
   * Filter function for events.
   * If provided, only events passing this filter are processed.
   * Useful for tenant-specific projections.
   */
  eventFilter?: (event: StoredEvent) => boolean;
}

/**
 * Internal registration entry with resolved options.
 */
export interface ResolvedRegistration<TState = unknown> {
  registration: ProjectionRegistration<TState>;
  options: Required<Omit<ProjectionRuntimeOptions, 'eventFilter'>> & {
    eventFilter?: ProjectionRuntimeOptions['eventFilter'];
  };
}

/**
 * Projection registry interface.
 *
 * Used by compiler-generated code to register projections,
 * and by the coordinator to get all registrations.
 */
export interface ProjectionRegistry {
  /**
   * Register a projection.
   *
   * Called by compiler-generated code during startup.
   * Throws if a projection with the same name is already registered.
   *
   * @param registration - Projection registration
   * @param options - Optional runtime options
   */
  register<TState>(
    registration: ProjectionRegistration<TState>,
    options?: ProjectionRuntimeOptions
  ): void;

  /**
   * Get all registrations.
   *
   * Used by the coordinator to start all projections.
   */
  getAll(): ResolvedRegistration[];

  /**
   * Get registration by name.
   *
   * @param name - Projection name
   * @returns Registration or undefined if not found
   */
  get(name: string): ResolvedRegistration | undefined;

  /**
   * Check if a projection is registered.
   *
   * @param name - Projection name
   */
  has(name: string): boolean;

  /**
   * Get count of registered projections.
   */
  count(): number;

  /**
   * Clear all registrations.
   *
   * Primarily for testing.
   */
  clear(): void;
}

