// Generated index
// DO NOT EDIT - this file is generated by spite-compiler

export * from "./handlers/counter.handlers.js";
export * from "./validators/counter.validator.js";
export { createRouter, routes } from "./router.js";
