// Generated router
// DO NOT EDIT - this file is generated by spite-compiler

import type { SpiteDB } from "@spitestack/spitedb";

import { createCounterHandlers } from "./handlers/counter.handlers.js";

/**
 * Route definitions.
 */
export const routes = {
  "POST /api/counter/:streamId/increment": {
    handler: "counter.increment",
    access: "internal"
  },
  "POST /api/counter/:streamId/decrement": {
    handler: "counter.decrement",
    access: "internal"
  },
  "POST /api/counter/:streamId/reset": {
    handler: "counter.reset",
    access: "internal"
  }
} as const;

/**
 * Creates the application router.
 */
export function createRouter(db: SpiteDB) {
  const handlers = {
    counter: createCounterHandlers(db)
  };

  return {
    routes,
    handlers
  };
}
