// Generated server
// DO NOT EDIT - this file is generated by spite-compiler

import { SpiteDB, ConcurrencyError } from "./runtime/spitedb.js";

import { createCounterHandlers, type CommandResult } from "./handlers/counter.handlers.js";

const PORT = Number(process.env["PORT"]) || 3000;
const DB_PATH = process.env["SPITEDB_PATH"] || "./data";

let db: SpiteDB;
let counterHandlers: ReturnType<typeof createCounterHandlers>;

async function handleRequest(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const method = request.method;
  const path = url.pathname;

  // Health check endpoint
  if (method === "GET" && path === "/health") {
    return Response.json({ status: "ok" });
  }

  // Parse route: POST /api/{aggregate}/:streamId/{command}
  const match = path.match(/^\/api\/([a-z_]+)\/([^/]+)\/([a-z_]+)$/);
  if (!match || method !== "POST") {
    return Response.json({ error: "Not Found" }, { status: 404 });
  }

  const [, aggregateName, streamId, commandName] = match;

  try {
    // Parse request body
    let input: unknown = undefined;
    const contentType = request.headers.get("content-type");
    if (contentType?.includes("application/json")) {
      const text = await request.text();
      if (text.trim()) {
        input = JSON.parse(text);
      }
    }

    // Route to handler
    if (aggregateName === "counter") {
      if (commandName === "increment") {
        const result = await counterHandlers.increment(streamId!, input, db);
        return Response.json(result);
      }
      if (commandName === "decrement") {
        const result = await counterHandlers.decrement(streamId!, input, db);
        return Response.json(result);
      }
      if (commandName === "reset") {
        const result = await counterHandlers.reset(streamId!, db);
        return Response.json(result);
      }
    }

    return Response.json({ error: "Not Found" }, { status: 404 });
  } catch (error) {
    // Handle domain errors
    if (error instanceof ConcurrencyError) {
      return Response.json(
        { error: error.message, expected: error.expected, actual: error.actual },
        { status: 409 }
      );
    }

    // Handle validation errors
    if (error instanceof Error) {
      if (error.message.includes("validation") || error.message.includes("Invalid")) {
        return Response.json({ error: error.message }, { status: 400 });
      }
      // Likely a business rule error from the aggregate
      return Response.json({ error: error.message }, { status: 400 });
    }

    // Unknown error
    console.error("Unhandled error:", error);
    return Response.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

async function main() {
  console.log("Opening SpiteDB at", DB_PATH);
  db = await SpiteDB.open(DB_PATH);

  counterHandlers = createCounterHandlers(db);

  console.log(`Starting server on port ${PORT}...`);

  const server = Bun.serve({
    port: PORT,
    fetch: handleRequest,
  });

  console.log(`Server running at http://localhost:${server.port}`);

  // Graceful shutdown
  const shutdown = async (signal: string) => {
    console.log(`\nReceived ${signal}, shutting down...`);
    server.stop();
    await db.close();
    console.log("Shutdown complete");
    process.exit(0);
  };

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
}

main().catch((error) => {
  console.error("Failed to start server:", error);
  process.exit(1);
});
