/**
 * Embeds the SpiteDB runtime as string constants for standalone CLI binaries.
 *
 * This script reads the built runtime files and generates embedded.ts
 * with the content as exported string constants.
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const RUNTIME_DIR = join(import.meta.dir, "../lib/compiler/src/runtime");
const SPITEDB_DIR = join(import.meta.dir, "../lib/spitedb/dist");

// Read the runtime files
const spitedbJs = readFileSync(join(SPITEDB_DIR, "spitedb.js"), "utf-8");
const spitedbDts = readFileSync(join(SPITEDB_DIR, "spitedb.d.ts"), "utf-8");

// Generate the embedded.ts file
const content = `/**
 * Embedded SpiteDB runtime for standalone CLI binaries.
 *
 * This file is auto-generated by scripts/embed-runtime.ts
 * DO NOT EDIT MANUALLY
 */

// SpiteDB runtime bundle (${(spitedbJs.length / 1024).toFixed(1)} KB)
export const SPITEDB_JS = ${JSON.stringify(spitedbJs)};

// SpiteDB type declarations (${(spitedbDts.length / 1024).toFixed(1)} KB)
export const SPITEDB_DTS = ${JSON.stringify(spitedbDts)};
`;

writeFileSync(join(RUNTIME_DIR, "embedded.ts"), content);

console.log("Embedded runtime generated:");
console.log(`  - spitedb.js: ${(spitedbJs.length / 1024).toFixed(1)} KB`);
console.log(`  - spitedb.d.ts: ${(spitedbDts.length / 1024).toFixed(1)} KB`);
