/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of an append operation. */
export interface AppendResultNapi {
  /** First global position assigned */
  firstPos: number
  /** Last global position assigned */
  lastPos: number
  /** First stream revision assigned */
  firstRev: number
  /** Last stream revision assigned */
  lastRev: number
}
/** An event read from the store. */
export interface EventNapi {
  /** Global position in the log */
  globalPos: number
  /** Stream this event belongs to */
  streamId: string
  /** Revision within the stream */
  streamRev: number
  /** Timestamp when stored (Unix milliseconds) */
  timestampMs: number
  /** Event payload */
  data: Buffer
}
/** A batch of events for projection processing. */
export interface EventBatchNapi {
  /** Name of the projection this batch is for */
  projectionName: string
  /** Events in the batch */
  events: Array<EventNapi>
  /** Batch ID for acknowledgment */
  batchId: number
}
/** Column definition for a projection schema. */
export interface ColumnDefNapi {
  /** Column name */
  name: string
  /** Column type: "text", "integer", "real", "blob", "boolean" */
  colType: string
  /** Whether this column is part of the primary key */
  primaryKey: boolean
  /** Whether this column allows NULL values */
  nullable: boolean
  /** Default value (as JSON string) */
  defaultValue?: string
}
/** A single projection operation. */
export interface ProjectionOpNapi {
  /** Operation type: "upsert" or "delete" */
  opType: string
  /** Primary key value */
  key: string
  /** Row values for upsert (JSON string) */
  value?: string
}
/** Result of processing a batch - operations to apply. */
export interface BatchResultNapi {
  /** Name of the projection */
  projectionName: string
  /** Operations to apply */
  operations: Array<ProjectionOpNapi>
  /** Last global position processed (for checkpoint) */
  lastGlobalPos: number
}
/**
 * Admission control metrics snapshot.
 *
 * Provides visibility into the adaptive admission control system's state.
 */
export interface AdmissionMetricsNapi {
  /** Current max in-flight events (auto-adjusted based on observed latency) */
  currentLimit: number
  /** Observed p99 latency in milliseconds */
  observedP99Ms: number
  /** Target p99 latency in milliseconds (default: 60) */
  targetP99Ms: number
  /** Total requests that completed successfully */
  requestsAccepted: number
  /** Total requests that timed out due to backpressure */
  requestsRejected: number
  /** Ratio of rejected to total requests (0.0 to 1.0) */
  rejectionRate: number
  /** Number of times the controller adjusted the max_inflight limit */
  adjustments: number
}
export type SpiteDBNapi = SpiteDbNapi
/** NAPI wrapper for SpiteDB. */
export declare class SpiteDbNapi {
  /** Opens a SpiteDB database at the given path. */
  static open(path: string): Promise<SpiteDbNapi>
  /**
   * Appends events to a stream.
   *
   * @param streamId - The stream to append to
   * @param commandId - Unique command ID for idempotency
   * @param expectedRev - Expected revision: -1 for "any", 0 for "stream must not exist", >0 for exact revision
   * @param events - Array of event data buffers
   * @param tenant - Optional tenant ID (defaults to "default" for single-tenant apps)
   */
  append(streamId: string, commandId: string, expectedRev: number, events: Array<Buffer>, tenant?: string | undefined | null): Promise<AppendResultNapi>
  /** Reads events from a stream. */
  readStream(streamId: string, fromRev: number, limit: number): Promise<Array<EventNapi>>
  /** Reads events from the global log. */
  readGlobal(fromPos: number, limit: number): Promise<Array<EventNapi>>
  /** Gets the current revision of a stream. */
  getStreamRevision(streamId: string): Promise<number>
  /**
   * Initializes the projection registry.
   *
   * @param projectionsDir - Directory where projection databases will be stored.
   *                         Each projection will have its own .db file in this directory.
   */
  initProjections(projectionsDir: string): Promise<void>
  /**
   * Registers a projection with the given schema.
   *
   * Creates the projection's database file at `{projectionsDir}/{name}.db`.
   */
  registerProjection(name: string, schema: Array<ColumnDefNapi>): Promise<void>
  /**
   * Reads a row from a projection table by primary key (synchronous for proxy support).
   *
   * This method is synchronous because the magic proxy syntax (`table[key]`) requires
   * synchronous property access. The read uses blocking_lock internally.
   */
  readProjectionRow(projectionName: string, key: string): string | null
  /** Applies a batch of operations to a projection and updates the checkpoint. */
  applyProjectionBatch(batch: BatchResultNapi): Promise<void>
  /** Gets the next batch of events for a projection. */
  getProjectionEvents(projectionName: string, batchSize: number): Promise<EventBatchNapi | null>
  /** Gets the current checkpoint for a projection. */
  getProjectionCheckpoint(projectionName: string): Promise<number | null>
  /**
   * Gets current admission control metrics.
   *
   * Returns a snapshot of the adaptive admission control system's state,
   * useful for monitoring and debugging performance issues.
   *
   * @returns AdmissionMetricsNapi - current admission metrics snapshot
   */
  getAdmissionMetrics(): AdmissionMetricsNapi
}

// Re-export projection system types and functions
export type {
  ColumnDef,
  ColumnType,
  ErrorStrategy,
  Projection,
  ProjectionEvent,
  ProjectionOptions,
  ProjectionTable,
  RowData,
  SchemaDefinition,
  SchemaToRow,
} from './js/types';

export { projection, createProjectionProxy, ProjectionRunner } from './js/index';
